### PR TITLE
BLE Pairing and Encryption

### PR DESCRIPTION
**Pull request by unknownconstant**
This pull request is for an implementation of the BLE Security Manager which allows arduino devices to pair & encrypt connections using the HCI specification. Specifically, it implements Secure Connect / Numeric comparison.

The branch appears stable but I'm aware it may need some refactoring. An example sketch is included to show how to pair devices.

The branch supports encryption instigated by the central when the arduino is the peripheral.

### CODE REVIEW

**Comment by unknownconstant** [comment]
Pull request in relation to:  https://github.com/arduino-libraries/ArduinoBLE/issues/36 and https://github.com/unknownconstant/ArduinoBLE/issues/11

**Comment by shemminger** [comment]
Not all devices want to support pairing. This code doesn't seem to do that.
I would like if it were possible to respond "Pairing not supported" as described in Bluetooth Core Spec C.5.1

**Comment by unknownconstant** [comment]
Happy to take a look - which bit of the spec are you looking at for this? There are a number of volumes which have a C.5.1.

The code in this PR currently only supports the peripheral device, so if the device using this code does not support pairing then it shouldn't be set to require encryption. I understand for BLE that the central will instigate encryption only after the peripheral has sent an error response indicating insufficient encryption or authentication.

Volume 3, H 3.5.1 describes bonding flags in the pairing procedure. When testing I found that these flags did not affect whether an iPhone stored pairing data or not but I would welcome more info if you're able to test this or have any other insights.

**Comment by shemminger** [comment]
A little more background. I am building an Ardunio BLE device which emulates a proprietary BLE device that provides steering angle control for the bike training game Zwift.  The protocol is already reverse engineered (so thats easy). And the Nano BLE has magnetic sensor, and that can be used as directional input.  This is just a dumb BLE device (similar to Battery monitor etc).

The code works talking to Android, and probably MacOs. But does not work with Windows 10 the application connects, but then gets no data.  I suspect the lack of pairing support.  Doing full encryption is overkill for this application. Wondered if this would be enough to just respond with "not supported"

image

**Comment by shemminger** [comment]
I did some more experiments (and tried to learn about the twisted maze of BLE security).
It looks like just setting 0 in the auth request bits in the pairing response is enough to get what I need (pairing without encrypt).
BUT the value is hard coded in this version (see HCI.localAuthReq); looks like you weren't finished with that bit yet.

What would the API be for an application to override the default authentication request settings.
Something like:
   BLE.setLocalAuth(AuthReq)?

**Comment by shemminger** [comment]
Compile is catching this warning:
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::handleSecurityData(uint16_t, uint8_t, uint8_t*)':
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp:296:13: warning: 'i' may be used uninitialized in this function [-Wmaybe-uninitialized]
     for(int i; i<6; i++) peerAddress[5-i] = identityAddress->address[i];
             ^

Looks like missing i = 0

**Comment by shemminger** [comment]
Lots of other warnings now introduced./home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::handleSecurityData(uint16_t, uint8_t, uint8_t*)':
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp:271:8: warning: unused variable 'pairingFailed' [-Wunused-variable]
     } *pairingFailed = (PairingFailed*)data;
        ^~~~~~~~~~~~~
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp:320:7: warning: unused variable 'readPublicKeyCommand' [-Wunused-variable]
     } readPublicKeyCommand = {
       ^~~~~~~~~~~~~~~~~~~~
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::smCalculateLTKandConfirm(uint16_t, uint8_t*)':
/home/shemminger/Arduino/libraries/ArduinoBLE/src/utility/L2CAPSignaling.cpp:421:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=0; i<sizeof(Eb); i++){
                  ~^~~~~~~~

**Comment by unknownconstant** [comment]
Hi @shemminger , I've not been able to reproduce these errors using the standard Arduino compiler. Is this what you have used, or are you using another toolchain?

When cloning this library on another computer, a number of errors were generated as I had mistakenly included both this version, and the official release. It may be worth checking this?

**Comment by shemminger** [comment]
On Mon, 26 Apr 2021 02:51:12 -0700
unknownconstant ***@***.***> wrote:

> Hi @shemminger , I've not been able to reproduce these errors using the standard Arduino compiler. Is this what you have used, or are you using another toolchain?
> 
> When cloning this library on another computer, a number of errors were generated as I had mistakenly included both this version, and the official release. It may be worth checking this?
> 

I was just building with Arduino IDE on Debian 11.
It has GCC 10 as back end.

**Comment by AmirMahdiNassiri** [comment]
Any update on when we can have this feature released as an official release?

**Comment by unknownconstant** [comment]
I don't know, there seems to be a licence issue. I've signed but it states it's still pending which may be preventing a merge. We may be waiting on the Arduino team to review the code.

**Comment by alranel** [comment]
I'm so sorry for jumping late into this. It looks like there's an issue with CLAbot since I do see that the user @unknownconstant signed the CLA, but we can easily force that.
On the other hand, this pull request contains commits also from @eltos who doesn't seem to have gone through CLA. @eltos, it would be very nice if you could spend a few seconds for that! :)

**Comment by eltos** [comment]
@alranel CLA signed ✅

**Comment by muadiber** [comment]
@alranel can you merge pull request?

**Comment by brontesprocessing** [comment]
@alranel Any chance to have it merged any time soon?

**Review by alranel — APPROVED** [review]
I tested the examples with my Android phone and a Nano 33 BLE and they worked like a charm! :)

**Comment by brontesprocessing** [comment]
@alranel  It looks like the Pull Request is approved. What happens next? Is it possible that new release will be published soon? Thank you in advance!

**Comment by alranel** [comment]
Sorry for being so slow - just one last confirmation: did you write all this code or did you take any part of it from other sources?
Looking forward to merge this. :)

**Comment by mklemarczyk** [comment]
Do we progress or other implementation is needed?

**Comment by unknownconstant** [comment]
Unsure - AFAIK it's just waiting on being merged

**Comment by Uberflup** [comment]
The features provided by this would be great to have, looking forward to it being merged. 
Is this still waiting on resolution of a license issue?

**Comment by facchinm** [comment]
Yup we were still waiting for the CLA to be signed by all the commit authors but it looks like it was and the bot is not actually behaving correctly... I'm going to merge it anyway :wink:

**Comment by per1234** [comment]
For future reference, the reason the CLA check was not passing is because the check is done against the owner of each commit in the PR. The CLA is signed by your GitHub user account, so the commit can only be verified when its email address (as set via the [`user.email`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-useremail) Git configuration key) is associated with the GitHub account.

You can see that some of the commits from @unknownconstant had one email address configuration. For example:

https://api.github.com/repos/arduino-libraries/ArduinoBLE/commits/e5ccd3b2c3d21df29a1b246959e663bcbf9f153f

and other commits had another. For example:

https://api.github.com/repos/arduino-libraries/ArduinoBLE/commits/c66379882f727276b74c319c1ec9fa824fc96bf1

The bot attempts to communicate this situation in the comments:

>unknownconstant seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Pull request merged**
