### PR TITLE
Support esp32, esp32-C3, esp32-S3

### PR DESCRIPTION
**Pull request by dominsch**
### Who is this for?
There are at least 9 people that use ArduinoBLE on esp32 right now and with >600,000 Espressif SoCs sold daily that number might grow into the double digits.

### Why do we want this?
Running ArduinoBLE directly on Espressif chips outperforms all other available bluetooth stacks. Here is a table showing resource utilization after compiling the different libraries' respective scan examples:

| Stack | Storage Space | Dynamic Memory |
| --- | :---: |  --- |
| Bluedroid | `1029009 bytes (78%)` | `32572 bytes (9%)` |
| NimBLE | `549721 bytes (41%)` | `29452 bytes (8%)` |
| **ArduinoBLE** | `464501 bytes (35%)` | `25556 bytes (7%)` |

### Changes since my previous pull request:
- support for esp32-S3
- now works with the stable version of arduino-esp
- fixed crashes when restarting the BLE client as mentioned here: https://github.com/arduino-libraries/ArduinoBLE/issues/174#issuecomment-1214440623
- future chips should work out of the box without being added manually
- CI integration

### CODE REVIEW

**Comment by facchinm** [comment]
Wow, thank you so much for the contribution! I'm pretty sure this will increase the library usage to the double digit :wink:

**Comment by CP52** [comment]
I'm trying to add myself to 9 people that use this lib with ESP32 and Arduino IDE 2.0.3 ;-)

But I still have this problem with HCIVirtualTransport:

d:\Users\cpagu\Documents\Arduino\libraries\ArduinoBLE\src\utility\HCIVirtualTransport.h:27:36: fatal error: freertos/stream_buffer.h: No such file or directory
compilation terminated.

exit status 1

Compilation error: exit status 1

I tried to disinstall ArduinoBLE and reinstall ... before I used the Arduino ESP32 BLE, that is still present ... Any suggestion?

**Comment by dominsch** [comment]
You are likely using an older version of arduino core for esp32. Check your board manager and make sure you have at least version 2.0 installed. If it doesn't give you the option to upgrade please verify that you are using this board manager URL: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
I hope that helps

**Comment by CP52** [comment]
OK! Perfect! Disinstalled the ESP board and reinstalled ... now all seems to work ... many thanks from the 10th person using this lib for ESP32 ;-) and also infintete thanks for you job, dominsch!

**Comment by Craft058** [comment]
After many trial without any success I came to this page and apply your solution of updating the board manager with the suggested URL https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json and my ESP32 has discovered the services of my Oregon IDTW218H meteo station without any hesitation just using the Scan and PeripheralExplorer examples provided in the Arduino IDE. 
Thanks a lot dominsch !

**Comment by lyusupov** [comment]
@dominsch 
Is there any chance to add support for ESP32-P4 with assistance of ESP-Hosted ?
https://github.com/espressif/esp-hosted-mcu/tree/main/examples/host_bluedroid_host_only

**Pull request merged**
