### PR TITLE
Use Github workflows to compile examples and spell check

### PR DESCRIPTION
**Pull request by sandeepmistry**
Alternative to PR #31 and #32.

Uses `compile-examples` action from: https://github.com/arduino-libraries/actions

This will allow us to have a super minimal `.yml` file in all `arduino-libraries` repos, and re-use a common action from a central Github repo.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@facchinm @cmaglie @lxrobotics @mastrolinux @rsora  please review this along with https://github.com/arduino-libraries/actions/tree/master/compile-examples (which is based on https://help.github.com/en/articles/creating-a-docker-container-action).

@rsora was in favour of use Node.js instead of Docker + bash for the common Github action in terms of testability, but I think this is good to get us going for now. We can introduce Node.js down the road as needed.

**Comment by lxrobotics** [comment]
:+1: I like how clean everything is. Doesn't need a rocket scientist to comprehend what's happening. Nice work 😉

**Comment by rsora** [comment]
Please do not let bash proliferate :smile_cat:  

Anyway, the action properly hides the boilerplate so :+1: from me.

May I suggest to move the also for the https://github.com/arduino-libraries/actions/tree/master/compile-examples code to https://github.com/arduino/actions? 
This way we will have a single consistent point of access for all our actions in the future (good also for us maintainers and users).

**Comment by sandeepmistry** [comment]
I've added spell check support In: https://github.com/arduino-libraries/actions/tree/master/spell-check (it uses code spell) ... this works and I've fixed some spelling :)

> May I suggest to move the https://github.com/arduino-libraries/actions/tree/master/compile-examples code to https://github.com/arduino/actions?

@rsora I think I'm ok with this, we might need to rename the action names to indicate they are for Arduino Libraries only, with we get for free sort of because of `arduino-libraries/actions`

**Comment by rsora** [comment]
> @rsora I think I'm ok with this, we might need to rename the action names to indicate they are for Arduino Libraries only, with we get for free sort of because of `arduino-libraries/actions`

@sandeepmistry as per https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory we should be able to do something like this 
`uses: arduino/actions/libraries/compile-examples@master` WDYT?

**Comment by sandeepmistry** [comment]
> uses: arduino/actions/libraries/compile-examples@master WDYT?

@rsora excellent suggestion! Stay tuned for a pull request in that repo! #hackoberfest

**Comment by sandeepmistry** [comment]
This should be good to go now, I've removed the Travis CI config as well. We need to re-add the badges to the read me once merged.

**Pull request merged**
