### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by roleroz**
- Reorder member initialization on BLELocalCharacteristic
- Remove unused variables in:
  - `HCIClass::tryResolveAddress`
  - `HCIClass::handleEventPkt` (the whole else if statement did nothing)
  - `L2CAPSignalingClass::handleSecurityData` (one initialization should be inside of _BLE_TRACE_
  - `BluetoothCryptoToolbox::f5`
  - `BluetoothCryptoToolbox::testAh`
  - `BluetoothCryptoToolbox::testg2`
- Uninitialized variable in `L2CAPSignalingClass::handleSecurityData`

There is still a warning in, which I cannot fix without more information (specifically what is the case 0x0A named):

```text
ArduinoBLE/src/utility/HCI.cpp:991:7: warning: case value '10' not in enumerated type 'LE_META_EVENT' [-Wswitch]
       case 0x0A:{
       ^~~~
```

### CODE REVIEW

**Comment by roleroz** [comment]
Friendly ping on this

**Comment by roleroz** [comment]
How can I get this PR reviewed?

**Comment by facchinm** [comment]
@roleroz 
sorry for the late response but last couple of months have been very intensive :slightly_smiling_face: 
I reviewed the PR and the fixes looked good (in particular the BLELocalCharacteristic constructor was bothering me every time I compiled :sweat_smile: ).
Thanks so much!

**Comment by roleroz** [comment]
Commented on the issue assigned to this, this PR didn't fix all of it, there is one case left. If you can answer the question I put there (https://github.com/arduino-libraries/ArduinoBLE/issues/310#issuecomment-1666064563) I'll gladly create another PR for that

**Pull request merged**
